version: "3"
services:
  mysql:
    image: mysql:8.0.22
    container_name: students-payment-preferences-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=students
    ports:
      - "3306:3306"
    volumes:
      - ./DB/create-tables.sql:/docker-entrypoint-initdb.d/dump.sql

  backend:
    build:
      context: BE
      dockerfile: Dockerfile
    image: be-image
    container_name: students-payment-preferences-be
    ports: 
      - "8080:8080"
    depends_on:
      - mysql
      




