version: "3"
services:
  mysql:
    image: mysql:8.0.22
    container_name: students-payment-preferences-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=students
    ports:
      - "3306:3306"
    volumes:
      - ./DB/create-tables.sql:/docker-entrypoint-initdb.d/dump.sql
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]

  backend:
    build:
      context: .
      dockerfile: BE/Dockerfile
    image: be-image
    container_name: students-payment-preferences-be
    ports: 
      - "8080:8080"
    depends_on:
      - mysql
    command: ["./wait-for.sh", "mysql:3306", "--", "npm", "start"]

  frontend:
    build:
      context: .
      dockerfile: fe/Dockerfile
    image: fe-image
    container_name: students-payment-preferences-fe
    ports: 
      - "3000:3000"
    depends_on:
      - backend
    command: ["./wait-for.sh", "backend:8080", "--", "npm", "start"]





